mysql:
  dataBase: bot
  userName: root
  passWord: root
  port: 3306
  driverName: mysql
  host: 127.0.0.1
  log_Level: dev

logger:
  level: info
  prefix: '[OPQBot-Roy]'
  director: log
  show-line: true
  log-in-console: true

system:
  host: 0.0.0.0
  post: 8080
  env: release